// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bggxrbrnmrskyackbsax.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJnZ3hyYnJubXJza3lhY2tic2F4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNzc4NTAsImV4cCI6MjA2MDk1Mzg1MH0.oVWzXiKM3AA5ngRqTgzLyOWCguNFV5aTL81wkYO2VUc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);